// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZxq672IkeNnD4biemqhd6IZgyW_87Bes',
    appId: '1:1039473596526:web:449b0f8f60f2f356206e7f',
    messagingSenderId: '1039473596526',
    projectId: 'miftek-assist',
    authDomain: 'miftek-assist.firebaseapp.com',
    databaseURL: 'https://miftek-assist-default-rtdb.firebaseio.com',
    storageBucket: 'miftek-assist.appspot.com',
    measurementId: 'G-XKJV6L1K3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVNkCy6N-9zxV2uYmd9cgM_jjWLMr9F2s',
    appId: '1:1039473596526:android:7b50be1845057d13206e7f',
    messagingSenderId: '1039473596526',
    projectId: 'miftek-assist',
    databaseURL: 'https://miftek-assist-default-rtdb.firebaseio.com',
    storageBucket: 'miftek-assist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrH2xiPHksM0iqgx8iZ57ctiMtXIfz7CI',
    appId: '1:1039473596526:ios:de3ddd08537d9295206e7f',
    messagingSenderId: '1039473596526',
    projectId: 'miftek-assist',
    databaseURL: 'https://miftek-assist-default-rtdb.firebaseio.com',
    storageBucket: 'miftek-assist.appspot.com',
    iosBundleId: 'com.example.miftekAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrH2xiPHksM0iqgx8iZ57ctiMtXIfz7CI',
    appId: '1:1039473596526:ios:de3ddd08537d9295206e7f',
    messagingSenderId: '1039473596526',
    projectId: 'miftek-assist',
    databaseURL: 'https://miftek-assist-default-rtdb.firebaseio.com',
    storageBucket: 'miftek-assist.appspot.com',
    iosBundleId: 'com.example.miftekAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZxq672IkeNnD4biemqhd6IZgyW_87Bes',
    appId: '1:1039473596526:web:e6551e1d4c5aa48a206e7f',
    messagingSenderId: '1039473596526',
    projectId: 'miftek-assist',
    authDomain: 'miftek-assist.firebaseapp.com',
    databaseURL: 'https://miftek-assist-default-rtdb.firebaseio.com',
    storageBucket: 'miftek-assist.appspot.com',
    measurementId: 'G-YK69FP0J2Z',
  );
}
